#!/bin/bash
# Startup script for metad
#
# chkconfig: 2345 20 80
# description: Starts and stops metad

. /etc/init.d/functions

prog=metad
METAD_BIN=/usr/local/bin/metad
if [[ ! -e $METAD_BIN ]]; then
  echo "$prog binary not found."
  exit 5
fi

ETCD_HOST="http://127.0.0.1:2379"
METAD_LOCKFILE="/var/lock/subsys/$prog"
METAD_LOGFILE=/data0/logs/$prog.log
METAD_PIDFILE=/var/run/$prog.pid

start() {
  started=$(status -p "$METAD_PIDFILE" "$METAD_BIN")
  [[ $started =~ running ]] && echo $started && return 1

  echo -n $"Starting $prog: "
  $METAD_BIN --backend etcdv3 --nodes $ETCD_HOST \
  --log_level debug --listen :8080 \
  --listen_manage 0.0.0.0:9611 \
  3>&1 2>&1 1>&$METAD_LOGFILE &
  RETVAL=$?
  echo $! > $METAD_PIDFILE
  [[ $RETVAL ]] && success || failure
  [[ $RETVAL ]] && touch "$METAD_LOCKFILE"
  return $RETVAL
}

stop() {
  echo -n $"Stopping $prog: "
  killproc -p "$METAD_PIDFILE" "$METAD_BIN"

  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -fr "$METAD_LOCKFILE"
  return $RETVAL
}

case $1 in
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop
    start
    ;;

  status)
    status "$METAD_BIN"
    RETVAL=$?
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|status}"
    RETVAL=1
    ;;
esac

exit $RETVAL